# TODO to args

exchanges:
  - binance
  #- kucoin

market_types:
#  - stock
  - futures

logger:
  console: debug
  file: debug
  # telegram

telegram:
  chat_id: ''
  bot_token: ''

credentials:
  stock:
    binance:
      api_key: ''
      secret_key: ''

  futures:
    binance:
      api_key: ''
      secret_key: ''

strategy:
  folder: 'strategy'
